services:
  - type: web
    name: retailiq-sales-forecast
    runtime: python
    # We build from the very root to ensure the ML models are accessible
    buildCommand: pip install -r sales-forecast/sales_forecasting/flask_app/requirements_flask.txt
    # Start the app from the specific subdirectory
    startCommand: gunicorn --chdir sales-forecast/sales_forecasting/flask_app app:app
    envVars:
      - key: DATABASE_URL
        sync: false # You will paste your Neon database URL in the Render dashboard
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
