"""initial setup

Revision ID: 57dcf4bb9441
Revises: 
Create Date: 2026-04-10 17:56:06.233688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57dcf4bb9441'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_logs', schema=None) as batch_op:
        batch_op.alter_column('prediction',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('prediction_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_pl_cat'))
        batch_op.drop_index(batch_op.f('idx_pl_created'))
        batch_op.drop_index(batch_op.f('idx_pl_region'))
        batch_op.drop_index(batch_op.f('idx_pl_user'))
        batch_op.create_index(batch_op.f('ix_prediction_logs_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_logs_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_logs_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('prediction_logs_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('store_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=mysql.ENUM('Clothing', 'Electronics', 'Furniture', 'Groceries', 'Toys', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('region',
               existing_type=mysql.ENUM('East', 'North', 'South', 'West', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('inventory_level',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('units_sold',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('units_ordered',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('discount',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('weather_condition',
               existing_type=mysql.ENUM('Sunny', 'Cloudy', 'Rainy', 'Snowy', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=30),
               nullable=True)
        batch_op.alter_column('holiday_promotion',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('competitor_pricing',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('seasonality',
               existing_type=mysql.ENUM('Spring', 'Summer', 'Autumn', 'Winter', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_sr_cat'))
        batch_op.drop_index(batch_op.f('idx_sr_catdate'))
        batch_op.drop_index(batch_op.f('idx_sr_date'))
        batch_op.drop_index(batch_op.f('idx_sr_product'))
        batch_op.drop_index(batch_op.f('idx_sr_region'))
        batch_op.drop_index(batch_op.f('idx_sr_store'))
        batch_op.drop_index(batch_op.f('idx_sr_storecat'))
        batch_op.create_index(batch_op.f('ix_sales_records_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_records_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_records_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_records_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_records_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_records_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('sales_records_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('record_date')
        batch_op.drop_column('demand_forecast')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('plan',
               existing_type=mysql.ENUM('free', 'pro', 'team', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'free'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('idx_email'))
        batch_op.drop_index(batch_op.f('idx_plan'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('idx_plan'), ['plan'], unique=False)
        batch_op.create_index(batch_op.f('idx_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('plan',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('free', 'pro', 'team', collation='utf8mb4_unicode_ci'),
               existing_nullable=False,
               existing_server_default=sa.text("'free'"))

    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('demand_forecast', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=True))
        batch_op.add_column(sa.Column('record_date', sa.DATE(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sales_records_ibfk_1'), 'users', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_sales_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_sales_records_store_id'))
        batch_op.drop_index(batch_op.f('ix_sales_records_region'))
        batch_op.drop_index(batch_op.f('ix_sales_records_product_id'))
        batch_op.drop_index(batch_op.f('ix_sales_records_date'))
        batch_op.drop_index(batch_op.f('ix_sales_records_created_at'))
        batch_op.drop_index(batch_op.f('ix_sales_records_category'))
        batch_op.create_index(batch_op.f('idx_sr_storecat'), ['store_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('idx_sr_store'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_sr_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('idx_sr_product'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_sr_date'), ['record_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_sr_catdate'), ['category', 'record_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_sr_cat'), ['category'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('seasonality',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('Spring', 'Summer', 'Autumn', 'Winter', collation='utf8mb4_unicode_ci'),
               nullable=False)
        batch_op.alter_column('competitor_pricing',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('holiday_promotion',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('weather_condition',
               existing_type=sa.String(length=30),
               type_=mysql.ENUM('Sunny', 'Cloudy', 'Rainy', 'Snowy', collation='utf8mb4_unicode_ci'),
               nullable=False)
        batch_op.alter_column('discount',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('units_ordered',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('units_sold',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('inventory_level',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('region',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('East', 'North', 'South', 'West', collation='utf8mb4_unicode_ci'),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('Clothing', 'Electronics', 'Furniture', 'Groceries', 'Toys', collation='utf8mb4_unicode_ci'),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=False)
        batch_op.alter_column('store_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('date')

    with op.batch_alter_table('prediction_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('prediction_logs_ibfk_1'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_prediction_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_prediction_logs_region'))
        batch_op.drop_index(batch_op.f('ix_prediction_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_prediction_logs_category'))
        batch_op.create_index(batch_op.f('idx_pl_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_pl_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('idx_pl_created'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_pl_cat'), ['category'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('prediction_date',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('prediction',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
